apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: yugastore-gitops-deployer
  namespace: default
spec:
  fetch:
  - git:
      url: https://github.com/tfynes-pivotal/yugastore-k8s
      ref: origin/master
      subPath: workloads
  - git:
      url: https://github.com/tfynes-pivotal/yugastore-k8s
      ref: origin/master
      subPath: scg-routes

  template:
  - ytt: {}
  deploy: 
  - kapp: {}
