apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: cart-gateway-route
spec:
  service:
    name: cart
  routes:
  - predicates:
      - Path=/cart/add/**
    order: 0
    filters:
      - StripPrefix=2
      - PrefixPath=/cart-microservice/shoppingCart/addProduct
      - AddRequestParam=userid,1
    uri: http://cart-default.gkelabeast.tap.fynesy.com
  
  - predicates:
      - Path=/cart/get/**
    order: 0
    filters:
      - StripPrefix=2
      - PrefixPath=/cart-microservice/shoppingCart/productsInCart
      - AddRequestParam=userid,1
    uri: http://cart-default.gkelabeast.tap.fynesy.com

  - predicates:
      - Path=/cart/**
    order: 1 
    filters:
      - StripPrefix=1
      - PrefixPath=/cart-microservice
    uri: http://cart-default.gkelabeast.tap.fynesy.com
